name: Create Review Task

on:
  workflow_dispatch:

jobs:
  create-review-task:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Execute Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python script/create_review_task.py \
            '${{ toJson(github.event.pull_request) }}' \
            '${{ github.repository }}' \
            '${{ github.event.pull_request.number }}'
