name: PR Comment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Add comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "Hello! This comment was added automatically when the PR was opened or reopened."
            })
